version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: veriats-minio
    ports:
      - "9000:9000" # API Port (S3 compatible API)
      - "9001:9001" # Web UI Console
    environment:
      # Credenciales de Administrador súper sencillas para desarrollo local
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  minio_data:
