"""add_company_name_to_users

Revision ID: 209a4736c722
Revises: 453305ed361c
Create Date: 2026-01-23 20:59:02.549505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209a4736c722'
down_revision = '453305ed361c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
