"""add_cvs_table

Revision ID: 453305ed361c
Revises: 
Create Date: 2026-01-23 19:28:13.744599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453305ed361c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
